### ISSUE TITLE
not really issue

### ISSUE THREAD

**Issue by ghost** [MuffinMario/Old-Darkorbit-Project-2009-Cpp#1]
Hey, nice work with the server man :D! Really nice work!

Could you post here some contant info of yours? (skype , steam)
Maybe we could try 1 v 1 fight on the server?

**Comment by ghost** [comment]
Not really an issue, you can delete this if you will find it annoying....
I will wait for your response

**Comment by MuffinMario** [comment]
Well go on and work on your own thing, the tools are here prepared for you :)
I will **not** open a server.
