### ISSUE TITLE
this is not issue

### ISSUE THREAD

**Issue by CombineCrusher** [MuffinMario/Old-Darkorbit-Project-2009-Cpp#10]
Can you make about how to make video pls idk how to make this things

**Comment by CombineCrusher** [comment]
Can you make about how to make video pls idk how to make this things

**Comment by MuffinMario** [comment]
I will not. If you do not know how to use these things, you should not use them.

**Comment by CombineCrusher** [comment]
I wanted to experience the old darkorbit experience
