### ISSUE TITLE
Not Issues

### ISSUE THREAD

**Issue by ste-giordano95** [MuffinMario/Old-Darkorbit-Project-2009-Cpp#4]
Hi, can share a cms compatible for test emulator? Thanks you!

and i have #error You built this project wrong. Decide if you want to build the policy or the game server or both

**Comment by MuffinMario** [comment]
I have just pushed a new total revamp that had been lying on my desktop for months now :) There also is a htdocs example that only contains a spacemap test webpage to enter.

The #error message cannot appear anymore since I have split both projects into their own projects now. Read the README to know what libraries you need to use. For further questions you can use this thread.

**Comment by ste-giordano95** [comment]
New Error : (i have install all library)
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1104	cannot open file 'mysqlclient-d.lib'	GameServer	\Old-Darkorbit-Project-2009-Cpp-master\Old-Darkorbit-Project-2009-Cpp-master\spacemap server\GameServer\LINK	1	


I have only mysqlclient.lib.

**Comment by MuffinMario** [comment]
~~On my computer they both have the same bytesize, perhaps just rename it and remove the -d~~

**Comment by MuffinMario** [comment]
On revision, that is incorrect. Perhaps you have a wrong version?

You will have to download both, normal and Debug binaries from here https://downloads.mysql.com/archives/c-c/ and just put them in the same directory, append a -d to the name of the debug libraries.

**Comment by ste-giordano95** [comment]
ok, now work!

**Comment by ste-giordano95** [comment]
Error with cms http://prntscr.com/pfvclz

**Comment by MuffinMario** [comment]
Did you read the readme? You need to run both GameServer and PolicyServer for the GameServer to work. I don't know what URL youre calling aswell.

**Comment by ste-giordano95** [comment]
Sorry, work very well, thank u <3

**Comment by ste-giordano95** [comment]
i think priority are:
-Clan diplomacy system
-buy ammo on game
-change config

**Comment by MuffinMario** [comment]
Watch the database. It is absolutely horrible. You cannot have two configs with that database. I personally don't want to go through the whole effort of reinventing the database to give the player an inventory aswell as configs. 

Clan diplomacy and buying ammo in-game is not a difficult task to be fair :)

**Comment by ste-giordano95** [comment]
Hi, how do a query  with two condiction?

`
damage_t DBUtil::funcs::getDamage(id_t id, int conf)
{
	std::lock_guard<std::mutex> lock(database_mutex);
	damage_t dmg = 0;
	g_database_get.changeQuery("max_damage", "player_config", "config_id", conf, "player_id", id);
	dmg += g_database_get.getInt();

	return dmg;
}
`

**Comment by MuffinMario** [comment]
changeQuery is just a simple function. there has been no need to do two conditions yet. If you have further questions add me on Discord MuffinMario#1403

**Comment by CombineCrusher** [comment]
Can you make about how to make video pls idk how to make this things
