### ISSUE TITLE
how to affect toolset version for boost 1.70 installation

### ISSUE THREAD

**Issue by weeedy** [MuffinMario/Old-Darkorbit-Project-2009-Cpp#9]
thank you for your work!
i don´t know how to set the toolset version in installation of boost 1.70.
i got it here https://dl.bintray.com/boostorg/release/1.70.0/source/boost_1_70_0.zip or alternative there are other versions on https://www.boost.org/users/history/
for installation run bootstrap.bat and after that  .\b2

in my case i need toolset 140 because i use VisualStudio15, but at the moment boost only loads 120 toolset. Tried it on other system, where boost loads 142 toolset.

do you know how to affect toolset version in installation process of boost?

thank you for your work and attention!

**Comment by MuffinMario** [comment]
I am not a support for setting up boost. I recommend vcpkg as it is the easiest for Visual Studio. Best of luck!

**Comment by weeedy** [comment]
Thank you for your fast response! I only find newer versions than 1.70 via vcpkg. I'll contact boost support and post solution here if someone else has the same difficulties.
Thank you for your work and all the best!
